# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle daemon process. Useful for tweaking memory settings.
# Ensure important default jvmargs aren't overwritten. See https://github.com/gradle/gradle/issues/19750
# -Xmx6g: Sets maximum heap size to 6GB (adjust based on project size and system memory).
# -XX:+HeapDumpOnOutOfMemoryError: Generates a heap dump on OutOfMemoryError (for debugging).
# -Dfile.encoding=UTF-8: Sets the file encoding to UTF-8 (for consistency).
# -XX:+UseG1GC: Uses the G1 Garbage Collector (often improves GC pause times for larger heaps).
# -XX:MaxMetaspaceSize=1g: Sets maximum Metaspace size to 1GB (adjust if Metaspace OOM occurs).
org.gradle.jvmargs=-Xmx8g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:MaxMetaspaceSize=1g

# Allows Gradle to build projects (modules) in parallel in multi-project builds.
# Helps improve build speed, especially for decoupled projects.
org.gradle.parallel=true

# Enables the Gradle build cache.
# Reuses task outputs from previous builds if inputs haven't changed, significantly speeding up builds (local cache).
org.gradle.caching=true

# Enables the Gradle configuration cache (includes experimental features).
# Caches the result of the configuration phase to significantly speed up the start of subsequent builds.
# May have compatibility issues with some plugins or build scripts.
org.gradle.configuration-cache=true

# Enables the use of AndroidX libraries.
# Makes it clearer which packages are bundled with the Android OS and which are packaged with your app's APK.
# Standard for modern Android development. (See: https://developer.android.com/topic/libraries/support-library/androidx-rn)
android.useAndroidX=true

# Runs the R8 code shrinker and optimizer in 'full mode'.
# Enables more aggressive optimizations to reduce app size, but may increase release build time
# and requires careful configuration of Proguard/R8 rules and thorough testing.
android.enableR8.fullMode=true

# Ensures that each module's R class contains only resources declared directly in that module (Non-transitive R classes).
# Improves build performance in multi-module projects by reducing compile dependencies between modules.
android.nonTransitiveRClass=true

# Specifies the Kotlin code style for this project ('official' or 'obsolete').
kotlin.code.style=official